apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: retail-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::680464296107:role/project-bedrock-external-secrets-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts-sa
  namespace: retail-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::680464296107:role/project-bedrock-carts-role
