apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: retail-app
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: mysql-secret
    creationPolicy: Owner
    template:
      data:
        host: "project-bedrock-mysql.cu1myqu4afpd.us-east-1.rds.amazonaws.com"
        dbname: "orders"
        port: "3306"
        username: "{{ .username }}"
        password: "{{ .password }}"

  data:
    - secretKey: username
      remoteRef:
        key: "rds!db-62916505-7b9c-4e6e-a183-423e2b77c997"
        property: username

    - secretKey: password
      remoteRef:
        key: "rds!db-62916505-7b9c-4e6e-a183-423e2b77c997"
        property: password
