apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: retail-app
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: catalog-db-secret
    creationPolicy: Owner
    template:
      data:
        host: "project-bedrock-mysql.cu1myqu4afpd.us-east-1.rds.amazonaws.com"
        dbname: "catalog"
        port: "3306"
        username: "{{ .username }}"
        password: "{{ .password }}"

  data:
    - secretKey: username
      remoteRef:
        key: "rds!db-97ac3c05-3c24-4744-b6eb-8cd424f1c741"
        property: username

    - secretKey: password
      remoteRef:
        key: "rds!db-97ac3c05-3c24-4744-b6eb-8cd424f1c741"
        property: password
