apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: retail-app
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: postgres-secret
    creationPolicy: Owner
    template:
      data:
        host: "project-bedrock-postgres.cu1myqu4afpd.us-east-1.rds.amazonaws.com"
        dbname: "retailcatalog"
        port: "5432"
        username: "{{ .username }}"
        password: "{{ .password }}"

  data:
    - secretKey: username
      remoteRef:
        key: "rds!db-69b9c234-3b07-42b7-b843-8dd495e75ed9"
        property: username

    - secretKey: password
      remoteRef:
        key: "rds!db-69b9c234-3b07-42b7-b843-8dd495e75ed9"
        property: password
